import { Controller, Get } from '@overnightjs/core';
import { Request, Response } from 'express';

@Controller('standings')
export class StandingsController {
  @Get('')
  public getStandings(_: Request, res: Response): void {
    res.send({
      filters: {
        season: '2023',
      },
      area: {
        id: 2088,
        name: 'Germany',
        code: 'DEU',
        flag: 'https://crests.football-data.org/759.svg',
      },
      competition: {
        id: 2002,
        name: 'Bundesliga',
        code: 'BL1',
        type: 'LEAGUE',
        emblem: 'https://crests.football-data.org/BL1.png',
      },
      season: {
        id: 1592,
        startDate: '2023-08-18',
        endDate: '2024-05-18',
        currentMatchday: 34,
        winner: {
          id: 3,
          name: 'Bayer 04 Leverkusen',
          shortName: 'Leverkusen',
          tla: 'B04',
          crest: 'https://crests.football-data.org/3.png',
          address: 'Bismarckstr. 122-124 Leverkusen 51373',
          website: 'http://www.bayer04.de',
          founded: 1904,
          clubColors: 'Red / White / Black',
          venue: 'BayArena',
          lastUpdated: '2022-02-25T16:43:07Z',
        },
      },
      standings: [
        {
          stage: 'REGULAR_SEASON',
          type: 'TOTAL',
          group: null,
          table: [
            {
              position: 1,
              team: {
                id: 3,
                name: 'Bayer 04 Leverkusen',
                shortName: 'Leverkusen',
                tla: 'B04',
                crest: 'https://crests.football-data.org/3.png',
              },
              playedGames: 34,
              form: 'W,W,W,D,D',
              won: 28,
              draw: 6,
              lost: 0,
              points: 90,
              goalsFor: 89,
              goalsAgainst: 24,
              goalDifference: 65,
            },
            {
              position: 2,
              team: {
                id: 10,
                name: 'VfB Stuttgart',
                shortName: 'Stuttgart',
                tla: 'VFB',
                crest: 'https://crests.football-data.org/10.png',
              },
              playedGames: 34,
              form: 'W,W,W,D,L',
              won: 23,
              draw: 4,
              lost: 7,
              points: 73,
              goalsFor: 78,
              goalsAgainst: 39,
              goalDifference: 39,
            },
            {
              position: 3,
              team: {
                id: 5,
                name: 'FC Bayern München',
                shortName: 'Bayern',
                tla: 'FCB',
                crest: 'https://crests.football-data.org/5.svg',
              },
              playedGames: 34,
              form: 'L,W,L,W,W',
              won: 23,
              draw: 3,
              lost: 8,
              points: 72,
              goalsFor: 94,
              goalsAgainst: 45,
              goalDifference: 49,
            },
            {
              position: 4,
              team: {
                id: 721,
                name: 'RB Leipzig',
                shortName: 'RB Leipzig',
                tla: 'RBL',
                crest: 'https://crests.football-data.org/721.png',
              },
              playedGames: 34,
              form: 'D,D,D,W,W',
              won: 19,
              draw: 8,
              lost: 7,
              points: 65,
              goalsFor: 77,
              goalsAgainst: 39,
              goalDifference: 38,
            },
            {
              position: 5,
              team: {
                id: 4,
                name: 'Borussia Dortmund',
                shortName: 'Dortmund',
                tla: 'BVB',
                crest: 'https://crests.football-data.org/4.png',
              },
              playedGames: 34,
              form: 'W,L,W,L,D',
              won: 18,
              draw: 9,
              lost: 7,
              points: 63,
              goalsFor: 68,
              goalsAgainst: 43,
              goalDifference: 25,
            },
            {
              position: 6,
              team: {
                id: 19,
                name: 'Eintracht Frankfurt',
                shortName: 'Frankfurt',
                tla: 'SGE',
                crest: 'https://crests.football-data.org/19.svg',
              },
              playedGames: 34,
              form: 'D,D,L,L,W',
              won: 11,
              draw: 14,
              lost: 9,
              points: 47,
              goalsFor: 51,
              goalsAgainst: 50,
              goalDifference: 1,
            },
            {
              position: 7,
              team: {
                id: 2,
                name: 'TSG 1899 Hoffenheim',
                shortName: 'Hoffenheim',
                tla: 'TSG',
                crest: 'https://crests.football-data.org/2.png',
              },
              playedGames: 34,
              form: 'W,W,D,L,W',
              won: 13,
              draw: 7,
              lost: 14,
              points: 46,
              goalsFor: 66,
              goalsAgainst: 66,
              goalDifference: 0,
            },
            {
              position: 8,
              team: {
                id: 44,
                name: '1. FC Heidenheim 1846',
                shortName: 'Heidenheim',
                tla: 'HEI',
                crest: 'https://crests.football-data.org/44.svg',
              },
              playedGames: 34,
              form: 'W,D,D,W,L',
              won: 10,
              draw: 12,
              lost: 12,
              points: 42,
              goalsFor: 50,
              goalsAgainst: 55,
              goalDifference: -5,
            },
            {
              position: 9,
              team: {
                id: 12,
                name: 'SV Werder Bremen',
                shortName: 'Bremen',
                tla: 'SVW',
                crest: 'https://crests.football-data.org/12.svg',
              },
              playedGames: 34,
              form: 'W,D,D,W,W',
              won: 11,
              draw: 9,
              lost: 14,
              points: 42,
              goalsFor: 48,
              goalsAgainst: 54,
              goalDifference: -6,
            },
            {
              position: 10,
              team: {
                id: 17,
                name: 'SC Freiburg',
                shortName: 'Freiburg',
                tla: 'SCF',
                crest: 'https://crests.football-data.org/17.svg',
              },
              playedGames: 34,
              form: 'L,D,D,L,D',
              won: 11,
              draw: 9,
              lost: 14,
              points: 42,
              goalsFor: 45,
              goalsAgainst: 58,
              goalDifference: -13,
            },
            {
              position: 11,
              team: {
                id: 16,
                name: 'FC Augsburg',
                shortName: 'Augsburg',
                tla: 'FCA',
                crest: 'https://crests.football-data.org/16.png',
              },
              playedGames: 34,
              form: 'L,L,L,L,L',
              won: 10,
              draw: 9,
              lost: 15,
              points: 39,
              goalsFor: 50,
              goalsAgainst: 60,
              goalDifference: -10,
            },
            {
              position: 12,
              team: {
                id: 11,
                name: 'VfL Wolfsburg',
                shortName: 'Wolfsburg',
                tla: 'WOB',
                crest: 'https://crests.football-data.org/11.svg',
              },
              playedGames: 34,
              form: 'L,L,W,W,W',
              won: 10,
              draw: 7,
              lost: 17,
              points: 37,
              goalsFor: 41,
              goalsAgainst: 56,
              goalDifference: -15,
            },
            {
              position: 13,
              team: {
                id: 15,
                name: '1. FSV Mainz 05',
                shortName: 'Mainz',
                tla: 'M05',
                crest: 'https://crests.football-data.org/15.png',
              },
              playedGames: 34,
              form: 'W,W,D,D,D',
              won: 7,
              draw: 14,
              lost: 13,
              points: 35,
              goalsFor: 39,
              goalsAgainst: 51,
              goalDifference: -12,
            },
            {
              position: 14,
              team: {
                id: 18,
                name: 'Borussia Mönchengladbach',
                shortName: "M'gladbach",
                tla: 'BMG',
                crest: 'https://crests.football-data.org/18.png',
              },
              playedGames: 34,
              form: 'L,D,D,D,L',
              won: 7,
              draw: 13,
              lost: 14,
              points: 34,
              goalsFor: 56,
              goalsAgainst: 67,
              goalDifference: -11,
            },
            {
              position: 15,
              team: {
                id: 28,
                name: '1. FC Union Berlin',
                shortName: 'Union Berlin',
                tla: 'UNB',
                crest: 'https://crests.football-data.org/28.svg',
              },
              playedGames: 34,
              form: 'W,L,L,D,L',
              won: 9,
              draw: 6,
              lost: 19,
              points: 33,
              goalsFor: 33,
              goalsAgainst: 58,
              goalDifference: -25,
            },
            {
              position: 16,
              team: {
                id: 36,
                name: 'VfL Bochum 1848',
                shortName: 'Bochum',
                tla: 'BOC',
                crest: 'https://crests.football-data.org/36.png',
              },
              playedGames: 34,
              form: 'L,L,W,W,L',
              won: 7,
              draw: 12,
              lost: 15,
              points: 33,
              goalsFor: 42,
              goalsAgainst: 74,
              goalDifference: -32,
            },
            {
              position: 17,
              team: {
                id: 1,
                name: '1. FC Köln',
                shortName: '1. FC Köln',
                tla: 'KOE',
                crest: 'https://crests.football-data.org/1.png',
              },
              playedGames: 34,
              form: 'L,W,D,D,L',
              won: 5,
              draw: 12,
              lost: 17,
              points: 27,
              goalsFor: 28,
              goalsAgainst: 60,
              goalDifference: -32,
            },
            {
              position: 18,
              team: {
                id: 55,
                name: 'SV Darmstadt 98',
                shortName: 'Darmstadt',
                tla: 'SVD',
                crest: 'https://crests.football-data.org/55.png',
              },
              playedGames: 34,
              form: 'L,L,L,L,W',
              won: 3,
              draw: 8,
              lost: 23,
              points: 17,
              goalsFor: 30,
              goalsAgainst: 86,
              goalDifference: -56,
            },
          ],
        },
        {
          stage: 'REGULAR_SEASON',
          type: 'HOME',
          group: null,
          table: [
            {
              position: 1,
              team: {
                id: 3,
                name: 'Bayer 04 Leverkusen',
                shortName: 'Leverkusen',
                tla: 'B04',
                crest: 'https://crests.football-data.org/3.png',
              },
              playedGames: 17,
              form: '',
              won: 14,
              draw: 3,
              lost: 0,
              points: 45,
              goalsFor: 47,
              goalsAgainst: 11,
              goalDifference: 36,
            },
            {
              position: 2,
              team: {
                id: 5,
                name: 'FC Bayern München',
                shortName: 'Bayern',
                tla: 'FCB',
                crest: 'https://crests.football-data.org/5.svg',
              },
              playedGames: 17,
              form: '',
              won: 14,
              draw: 1,
              lost: 2,
              points: 43,
              goalsFor: 53,
              goalsAgainst: 12,
              goalDifference: 41,
            },
            {
              position: 3,
              team: {
                id: 10,
                name: 'VfB Stuttgart',
                shortName: 'Stuttgart',
                tla: 'VFB',
                crest: 'https://crests.football-data.org/10.png',
              },
              playedGames: 17,
              form: '',
              won: 13,
              draw: 3,
              lost: 1,
              points: 42,
              goalsFor: 50,
              goalsAgainst: 15,
              goalDifference: 35,
            },
            {
              position: 4,
              team: {
                id: 721,
                name: 'RB Leipzig',
                shortName: 'RB Leipzig',
                tla: 'RBL',
                crest: 'https://crests.football-data.org/721.png',
              },
              playedGames: 17,
              form: '',
              won: 11,
              draw: 4,
              lost: 2,
              points: 37,
              goalsFor: 40,
              goalsAgainst: 12,
              goalDifference: 28,
            },
            {
              position: 5,
              team: {
                id: 4,
                name: 'Borussia Dortmund',
                shortName: 'Dortmund',
                tla: 'BVB',
                crest: 'https://crests.football-data.org/4.png',
              },
              playedGames: 17,
              form: '',
              won: 10,
              draw: 3,
              lost: 4,
              points: 33,
              goalsFor: 37,
              goalsAgainst: 22,
              goalDifference: 15,
            },
            {
              position: 6,
              team: {
                id: 19,
                name: 'Eintracht Frankfurt',
                shortName: 'Frankfurt',
                tla: 'SGE',
                crest: 'https://crests.football-data.org/19.svg',
              },
              playedGames: 17,
              form: '',
              won: 7,
              draw: 8,
              lost: 2,
              points: 29,
              goalsFor: 29,
              goalsAgainst: 21,
              goalDifference: 8,
            },
            {
              position: 7,
              team: {
                id: 44,
                name: '1. FC Heidenheim 1846',
                shortName: 'Heidenheim',
                tla: 'HEI',
                crest: 'https://crests.football-data.org/44.svg',
              },
              playedGames: 17,
              form: '',
              won: 7,
              draw: 5,
              lost: 5,
              points: 26,
              goalsFor: 30,
              goalsAgainst: 26,
              goalDifference: 4,
            },
            {
              position: 8,
              team: {
                id: 12,
                name: 'SV Werder Bremen',
                shortName: 'Bremen',
                tla: 'SVW',
                crest: 'https://crests.football-data.org/12.svg',
              },
              playedGames: 17,
              form: '',
              won: 7,
              draw: 4,
              lost: 6,
              points: 25,
              goalsFor: 29,
              goalsAgainst: 26,
              goalDifference: 3,
            },
            {
              position: 9,
              team: {
                id: 16,
                name: 'FC Augsburg',
                shortName: 'Augsburg',
                tla: 'FCA',
                crest: 'https://crests.football-data.org/16.png',
              },
              playedGames: 17,
              form: '',
              won: 6,
              draw: 6,
              lost: 5,
              points: 24,
              goalsFor: 26,
              goalsAgainst: 26,
              goalDifference: 0,
            },
            {
              position: 10,
              team: {
                id: 15,
                name: '1. FSV Mainz 05',
                shortName: 'Mainz',
                tla: 'M05',
                crest: 'https://crests.football-data.org/15.png',
              },
              playedGames: 17,
              form: '',
              won: 6,
              draw: 5,
              lost: 6,
              points: 23,
              goalsFor: 23,
              goalsAgainst: 18,
              goalDifference: 5,
            },
            {
              position: 11,
              team: {
                id: 2,
                name: 'TSG 1899 Hoffenheim',
                shortName: 'Hoffenheim',
                tla: 'TSG',
                crest: 'https://crests.football-data.org/2.png',
              },
              playedGames: 17,
              form: '',
              won: 6,
              draw: 5,
              lost: 6,
              points: 23,
              goalsFor: 31,
              goalsAgainst: 31,
              goalDifference: 0,
            },
            {
              position: 12,
              team: {
                id: 36,
                name: 'VfL Bochum 1848',
                shortName: 'Bochum',
                tla: 'BOC',
                crest: 'https://crests.football-data.org/36.png',
              },
              playedGames: 17,
              form: '',
              won: 5,
              draw: 8,
              lost: 4,
              points: 23,
              goalsFor: 26,
              goalsAgainst: 29,
              goalDifference: -3,
            },
            {
              position: 13,
              team: {
                id: 28,
                name: '1. FC Union Berlin',
                shortName: 'Union Berlin',
                tla: 'UNB',
                crest: 'https://crests.football-data.org/28.svg',
              },
              playedGames: 17,
              form: '',
              won: 7,
              draw: 2,
              lost: 8,
              points: 23,
              goalsFor: 22,
              goalsAgainst: 30,
              goalDifference: -8,
            },
            {
              position: 14,
              team: {
                id: 11,
                name: 'VfL Wolfsburg',
                shortName: 'Wolfsburg',
                tla: 'WOB',
                crest: 'https://crests.football-data.org/11.svg',
              },
              playedGames: 17,
              form: '',
              won: 6,
              draw: 4,
              lost: 7,
              points: 22,
              goalsFor: 25,
              goalsAgainst: 25,
              goalDifference: 0,
            },
            {
              position: 15,
              team: {
                id: 17,
                name: 'SC Freiburg',
                shortName: 'Freiburg',
                tla: 'SCF',
                crest: 'https://crests.football-data.org/17.svg',
              },
              playedGames: 17,
              form: '',
              won: 5,
              draw: 7,
              lost: 5,
              points: 22,
              goalsFor: 28,
              goalsAgainst: 30,
              goalDifference: -2,
            },
            {
              position: 16,
              team: {
                id: 18,
                name: 'Borussia Mönchengladbach',
                shortName: "M'gladbach",
                tla: 'BMG',
                crest: 'https://crests.football-data.org/18.png',
              },
              playedGames: 17,
              form: '',
              won: 5,
              draw: 6,
              lost: 6,
              points: 21,
              goalsFor: 27,
              goalsAgainst: 26,
              goalDifference: 1,
            },
            {
              position: 17,
              team: {
                id: 1,
                name: '1. FC Köln',
                shortName: '1. FC Köln',
                tla: 'KOE',
                crest: 'https://crests.football-data.org/1.png',
              },
              playedGames: 17,
              form: '',
              won: 4,
              draw: 4,
              lost: 9,
              points: 16,
              goalsFor: 15,
              goalsAgainst: 28,
              goalDifference: -13,
            },
            {
              position: 18,
              team: {
                id: 55,
                name: 'SV Darmstadt 98',
                shortName: 'Darmstadt',
                tla: 'SVD',
                crest: 'https://crests.football-data.org/55.png',
              },
              playedGames: 17,
              form: '',
              won: 1,
              draw: 3,
              lost: 13,
              points: 6,
              goalsFor: 15,
              goalsAgainst: 44,
              goalDifference: -29,
            },
          ],
        },
        {
          stage: 'REGULAR_SEASON',
          type: 'AWAY',
          group: null,
          table: [
            {
              position: 1,
              team: {
                id: 3,
                name: 'Bayer 04 Leverkusen',
                shortName: 'Leverkusen',
                tla: 'B04',
                crest: 'https://crests.football-data.org/3.png',
              },
              playedGames: 17,
              form: '',
              won: 14,
              draw: 3,
              lost: 0,
              points: 45,
              goalsFor: 42,
              goalsAgainst: 13,
              goalDifference: 29,
            },
            {
              position: 2,
              team: {
                id: 10,
                name: 'VfB Stuttgart',
                shortName: 'Stuttgart',
                tla: 'VFB',
                crest: 'https://crests.football-data.org/10.png',
              },
              playedGames: 17,
              form: '',
              won: 10,
              draw: 1,
              lost: 6,
              points: 31,
              goalsFor: 28,
              goalsAgainst: 24,
              goalDifference: 4,
            },
            {
              position: 3,
              team: {
                id: 4,
                name: 'Borussia Dortmund',
                shortName: 'Dortmund',
                tla: 'BVB',
                crest: 'https://crests.football-data.org/4.png',
              },
              playedGames: 17,
              form: '',
              won: 8,
              draw: 6,
              lost: 3,
              points: 30,
              goalsFor: 31,
              goalsAgainst: 21,
              goalDifference: 10,
            },
            {
              position: 4,
              team: {
                id: 5,
                name: 'FC Bayern München',
                shortName: 'Bayern',
                tla: 'FCB',
                crest: 'https://crests.football-data.org/5.svg',
              },
              playedGames: 17,
              form: '',
              won: 9,
              draw: 2,
              lost: 6,
              points: 29,
              goalsFor: 41,
              goalsAgainst: 33,
              goalDifference: 8,
            },
            {
              position: 5,
              team: {
                id: 721,
                name: 'RB Leipzig',
                shortName: 'RB Leipzig',
                tla: 'RBL',
                crest: 'https://crests.football-data.org/721.png',
              },
              playedGames: 17,
              form: '',
              won: 8,
              draw: 4,
              lost: 5,
              points: 28,
              goalsFor: 37,
              goalsAgainst: 27,
              goalDifference: 10,
            },
            {
              position: 6,
              team: {
                id: 2,
                name: 'TSG 1899 Hoffenheim',
                shortName: 'Hoffenheim',
                tla: 'TSG',
                crest: 'https://crests.football-data.org/2.png',
              },
              playedGames: 17,
              form: '',
              won: 7,
              draw: 2,
              lost: 8,
              points: 23,
              goalsFor: 35,
              goalsAgainst: 35,
              goalDifference: 0,
            },
            {
              position: 7,
              team: {
                id: 17,
                name: 'SC Freiburg',
                shortName: 'Freiburg',
                tla: 'SCF',
                crest: 'https://crests.football-data.org/17.svg',
              },
              playedGames: 17,
              form: '',
              won: 6,
              draw: 2,
              lost: 9,
              points: 20,
              goalsFor: 17,
              goalsAgainst: 28,
              goalDifference: -11,
            },
            {
              position: 8,
              team: {
                id: 19,
                name: 'Eintracht Frankfurt',
                shortName: 'Frankfurt',
                tla: 'SGE',
                crest: 'https://crests.football-data.org/19.svg',
              },
              playedGames: 17,
              form: '',
              won: 4,
              draw: 6,
              lost: 7,
              points: 18,
              goalsFor: 22,
              goalsAgainst: 29,
              goalDifference: -7,
            },
            {
              position: 9,
              team: {
                id: 12,
                name: 'SV Werder Bremen',
                shortName: 'Bremen',
                tla: 'SVW',
                crest: 'https://crests.football-data.org/12.svg',
              },
              playedGames: 17,
              form: '',
              won: 4,
              draw: 5,
              lost: 8,
              points: 17,
              goalsFor: 19,
              goalsAgainst: 28,
              goalDifference: -9,
            },
            {
              position: 10,
              team: {
                id: 44,
                name: '1. FC Heidenheim 1846',
                shortName: 'Heidenheim',
                tla: 'HEI',
                crest: 'https://crests.football-data.org/44.svg',
              },
              playedGames: 17,
              form: '',
              won: 3,
              draw: 7,
              lost: 7,
              points: 16,
              goalsFor: 20,
              goalsAgainst: 29,
              goalDifference: -9,
            },
            {
              position: 11,
              team: {
                id: 16,
                name: 'FC Augsburg',
                shortName: 'Augsburg',
                tla: 'FCA',
                crest: 'https://crests.football-data.org/16.png',
              },
              playedGames: 17,
              form: '',
              won: 4,
              draw: 3,
              lost: 10,
              points: 15,
              goalsFor: 24,
              goalsAgainst: 34,
              goalDifference: -10,
            },
            {
              position: 12,
              team: {
                id: 11,
                name: 'VfL Wolfsburg',
                shortName: 'Wolfsburg',
                tla: 'WOB',
                crest: 'https://crests.football-data.org/11.svg',
              },
              playedGames: 17,
              form: '',
              won: 4,
              draw: 3,
              lost: 10,
              points: 15,
              goalsFor: 16,
              goalsAgainst: 31,
              goalDifference: -15,
            },
            {
              position: 13,
              team: {
                id: 18,
                name: 'Borussia Mönchengladbach',
                shortName: "M'gladbach",
                tla: 'BMG',
                crest: 'https://crests.football-data.org/18.png',
              },
              playedGames: 17,
              form: '',
              won: 2,
              draw: 7,
              lost: 8,
              points: 13,
              goalsFor: 29,
              goalsAgainst: 41,
              goalDifference: -12,
            },
            {
              position: 14,
              team: {
                id: 15,
                name: '1. FSV Mainz 05',
                shortName: 'Mainz',
                tla: 'M05',
                crest: 'https://crests.football-data.org/15.png',
              },
              playedGames: 17,
              form: '',
              won: 1,
              draw: 9,
              lost: 7,
              points: 12,
              goalsFor: 16,
              goalsAgainst: 33,
              goalDifference: -17,
            },
            {
              position: 15,
              team: {
                id: 1,
                name: '1. FC Köln',
                shortName: '1. FC Köln',
                tla: 'KOE',
                crest: 'https://crests.football-data.org/1.png',
              },
              playedGames: 17,
              form: '',
              won: 1,
              draw: 8,
              lost: 8,
              points: 11,
              goalsFor: 13,
              goalsAgainst: 32,
              goalDifference: -19,
            },
            {
              position: 16,
              team: {
                id: 55,
                name: 'SV Darmstadt 98',
                shortName: 'Darmstadt',
                tla: 'SVD',
                crest: 'https://crests.football-data.org/55.png',
              },
              playedGames: 17,
              form: '',
              won: 2,
              draw: 5,
              lost: 10,
              points: 11,
              goalsFor: 15,
              goalsAgainst: 42,
              goalDifference: -27,
            },
            {
              position: 17,
              team: {
                id: 28,
                name: '1. FC Union Berlin',
                shortName: 'Union Berlin',
                tla: 'UNB',
                crest: 'https://crests.football-data.org/28.svg',
              },
              playedGames: 17,
              form: '',
              won: 2,
              draw: 4,
              lost: 11,
              points: 10,
              goalsFor: 11,
              goalsAgainst: 28,
              goalDifference: -17,
            },
            {
              position: 18,
              team: {
                id: 36,
                name: 'VfL Bochum 1848',
                shortName: 'Bochum',
                tla: 'BOC',
                crest: 'https://crests.football-data.org/36.png',
              },
              playedGames: 17,
              form: '',
              won: 2,
              draw: 4,
              lost: 11,
              points: 10,
              goalsFor: 16,
              goalsAgainst: 45,
              goalDifference: -29,
            },
          ],
        },
      ],
    });
  }
}
